# Site settings
title: 'PowerShell Goodies' # Your Title
tagline: 'Twisted tales to make you shudder' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: rouge #pygments
baseurl: /TheBlog # the subpath of your site, e.g. /blog/
